/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_open_block = 2,
  sym_close_block = 3,
  aux_sym_code_token1 = 4,
  sym_document = 5,
  sym_haskell_block = 6,
  sym_code = 7,
  sym_line = 8,
  aux_sym_document_repeat1 = 9,
  aux_sym_code_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_open_block] = "open_block",
  [sym_close_block] = "close_block",
  [aux_sym_code_token1] = "code_token1",
  [sym_document] = "document",
  [sym_haskell_block] = "haskell_block",
  [sym_code] = "code",
  [sym_line] = "line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_open_block] = sym_open_block,
  [sym_close_block] = sym_close_block,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [sym_document] = sym_document,
  [sym_haskell_block] = sym_haskell_block,
  [sym_code] = sym_code,
  [sym_line] = sym_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_open_block] = {
    .visible = true,
    .named = true,
  },
  [sym_close_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_haskell_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 6,
  [14] = 9,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (eof) ADVANCE(2);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '}') ADVANCE(5);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_open_block);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_close_block);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_close_block);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (eof) ADVANCE(2);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_open_block] = ACTIONS(1),
    [sym_close_block] = ACTIONS(1),
    [aux_sym_code_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(17),
    [sym_haskell_block] = STATE(2),
    [sym_line] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_code_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_open_block] = ACTIONS(5),
    [aux_sym_code_token1] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_haskell_block] = STATE(3),
    [sym_line] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_code_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_open_block] = ACTIONS(5),
    [aux_sym_code_token1] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_haskell_block] = STATE(3),
    [sym_line] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_code_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_open_block] = ACTIONS(13),
    [aux_sym_code_token1] = ACTIONS(16),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      aux_sym_code_token1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_open_block,
    STATE(6), 1,
      aux_sym_code_repeat1,
  [13] = 4,
    ACTIONS(23), 1,
      sym_close_block,
    ACTIONS(25), 1,
      aux_sym_code_token1,
    STATE(10), 1,
      aux_sym_code_repeat1,
    STATE(18), 1,
      sym_code,
  [26] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_open_block,
    ACTIONS(31), 1,
      aux_sym_code_token1,
    STATE(6), 1,
      aux_sym_code_repeat1,
  [39] = 3,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      anon_sym_LF,
    ACTIONS(38), 2,
      sym_open_block,
      aux_sym_code_token1,
  [50] = 3,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_LF,
    ACTIONS(44), 2,
      sym_open_block,
      aux_sym_code_token1,
  [61] = 2,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 2,
      sym_open_block,
      aux_sym_code_token1,
  [69] = 3,
    ACTIONS(25), 1,
      aux_sym_code_token1,
    ACTIONS(46), 1,
      sym_close_block,
    STATE(13), 1,
      aux_sym_code_repeat1,
  [79] = 2,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 2,
      sym_open_block,
      aux_sym_code_token1,
  [87] = 2,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 2,
      sym_open_block,
      aux_sym_code_token1,
  [95] = 3,
    ACTIONS(29), 1,
      sym_close_block,
    ACTIONS(52), 1,
      aux_sym_code_token1,
    STATE(13), 1,
      aux_sym_code_repeat1,
  [105] = 1,
    ACTIONS(29), 2,
      sym_close_block,
      aux_sym_code_token1,
  [110] = 1,
    ACTIONS(55), 1,
      anon_sym_LF,
  [114] = 1,
    ACTIONS(57), 1,
      anon_sym_LF,
  [118] = 1,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
  [122] = 1,
    ACTIONS(61), 1,
      sym_close_block,
  [126] = 1,
    ACTIONS(63), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 13,
  [SMALL_STATE(6)] = 26,
  [SMALL_STATE(7)] = 39,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 61,
  [SMALL_STATE(10)] = 69,
  [SMALL_STATE(11)] = 79,
  [SMALL_STATE(12)] = 87,
  [SMALL_STATE(13)] = 95,
  [SMALL_STATE(14)] = 105,
  [SMALL_STATE(15)] = 110,
  [SMALL_STATE(16)] = 114,
  [SMALL_STATE(17)] = 118,
  [SMALL_STATE(18)] = 122,
  [SMALL_STATE(19)] = 126,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_haskell_block, 3, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_haskell_block, 3, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_haskell_block, 4, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_haskell_block, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_haskell_block, 5, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_haskell_block, 5, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_alex(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "alex",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
